AWSTemplateFormatVersion: 2010-09-09
Description: >
  Amazon Connect instance CloudFormation template.
  Creates an Amazon Connect Instance, Hours of Operation.

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment to deploy into
    AllowedValues: [dev, uat, prod]

Resources:
  AmazonConnectInstance:
    Type: AWS::Connect::Instance
    Properties:
      Attributes:
        ContactflowLogs: true
        InboundCalls: true
        OutboundCalls: false
      IdentityManagementType: CONNECT_MANAGED
      InstanceAlias: !Join ['-', [!Join ['-', [summit-demo, !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]], !Ref Environment]]

  HoursOfOperation:
    Type: AWS::Connect::HoursOfOperation
    Properties:
      Name: Office Hours
      Description: Office Hours
      InstanceArn: !GetAtt AmazonConnectInstance.Arn
      TimeZone: Asia/Singapore
      Config:
        - Day: MONDAY
          EndTime:
            Hours: 19
            Minutes: 0
          StartTime:
            Hours: 9
            Minutes: 30
        - Day: TUESDAY
          EndTime:
            Hours: 19
            Minutes: 0
          StartTime:
            Hours: 9
            Minutes: 30
        - Day: WEDNESDAY
          EndTime:
            Hours: 19
            Minutes: 0
          StartTime:
            Hours: 9
            Minutes: 30
        - Day: THURSDAY
          EndTime:
            Hours: 19
            Minutes: 0
          StartTime:
            Hours: 9
            Minutes: 30
        - Day: FRIDAY
          EndTime:
            Hours: 19
            Minutes: 0
          StartTime:
            Hours: 9
            Minutes: 30
